server:
  paths:
    # root: 
    # temp: 

# Next section covers other servers that application connects to over http(s)
servers:
  # environment: 

# Values in next section will be directly sent to Flask's configuration
#   Flask expects them to all be UPPERCASE
flask:
# application database secret keys etc need to configure here
  DEBUG: True
  DATABASE_CONNECT_OPTIONS: {}

# Report Broker Database
# report_broker:


# FileStorage Database
# filestorage:
#  configure file storage db here

# attachments:
#   configure attachements here


# These values do not fit into any other section
other:
  font_family: Arial,Open Sans
